# Generated by Django 4.2.20 on 2025-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayworldData',
            fields=[
                ('sender_mobile_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
