# Generated by Django 4.2.20 on 2025-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_payworlddata_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayIFSCData',
            fields=[
                ('ifsc_code', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
