# Generated by Django 4.2.20 on 2025-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_razorpayifscdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayworldData2',
            fields=[
                ('sender_mobile_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
