# Generated by Django 4.2.20 on 2025-06-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_payworlddata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaynearbyData',
            fields=[
                ('mobile_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayIFSCData2',
            fields=[
                ('ifsc_code', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
