# Generated by Django 4.2.20 on 2025-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_apipricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
