# Generated by Django 4.2.20 on 2025-07-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cf_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
