# Generated by Django 4.2.20 on 2025-07-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction_cf_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credited_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
