"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os

from corsheaders.defaults import default_headers

from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

GHUNT_CREDS_PATH = os.path.join(BASE_DIR, 'secrets', 'creds.m')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yyr!ycnt3t8(cgrz3vydwxv%^e9=p-nd8d1oypmk75q2^whoty'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# ALLOWED_HOSTS = ['16.171.113.56', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'rest_framework',
    'corsheaders',
    'core',
    'custom_auth',
    'hudsonrock',
    'user_activities',
    'mobile',
    'payments',
    'leak_data',
    'secondary',
    'digital_intelligence',
    'holehe_util',
    'sherlock_util',
]

INSTALLED_APPS += EXTERNAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.GlobalExceptionMiddleware',  # Add this line
]

EXTERNAL_MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
]

MIDDLEWARE += EXTERNAL_MIDDLEWARE

GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET')

AWS_ACCESS_TOKEN = os.environ.get('AWS_DYNAMODB_ACCESS_TOKEN')
AWS_SECURITY_ACCESS_TOKEN = os.environ.get('AWS_DYNAMODB_SECURITY_ACCESS_TOKEN')
AWS_DYNAMO_REGION_NAME = os.environ.get('AWS_DYNAMODB_REGION_NAME')
DYNAMODB_LEAKED_TABLE_NAME = os.environ.get('AWS_DYNAMODB_LEAKED_TABLE_NAME')
DYNAMODB_JOBSEEKER_TABLE_NAME = os.environ.get('AWS_DYNAMODB_JOBSEEKER_TABLE_NAME')
DYNAMODB_CORPORATE_TABLE_NAME = os.environ.get('AWS_DYNAMODB_CORPORATE_TABLE_NAME')
DYNAMODB_ZOMATO_TABLE_NAME=os.environ.get('AWS_DYNAMODB_ZOMATO_TABLE_NAME')

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # Set to True only in development
ALLOWED_HOSTS = ['172.31.27.231', '*', 'localhost']


CORS_ALLOW_HEADERS = list(default_headers) + [
    'clientinfo',  # ❗ add your custom header name here, lowercase
]

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'USER_ID_FIELD': 'email',  # Use email instead of id
    'USER_ID_CLAIM': 'email',  # Use email in the token claims
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTH_USER_MODEL = 'custom_auth.CustomUser'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL CONFIGURATION
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'  # Use Outlook SMTP server
EMAIL_PORT = 587  # Default port for SMTP with TLS
EMAIL_USE_TLS = True  # Use TLS to secure the connection
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")  # Your full email address
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")


# CELERY
# Celery settings
CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")  # Redis URL (for EC2 Redis)
# CELERY_BROKER_URL = "redis://localhost:6379/0"  # Redis URL (for EC2 Redis)
# print("REDIS URL", os.environ.get("REDIS_URL"))
# Or for ElastiCache Redis (use the endpoint from ElastiCache)
# CELERY_BROKER_URL = 'redis://<elasticache-redis-endpoint>:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# CACHE
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SSL": True
        }
    }
}


CASHFREE_CLIENT_ID = os.environ.get("CASHFREE_CLIENT_ID")
CASHFREE_CLIENT_SECRET = os.environ.get("CASHFREE_CLIENT_SECRET")
CASHFREE_WEBHOOK_SECRET = os.environ.get("CASHFREE_WEBHOOK_SECRET")
CASHFREE_ENV = 'SANDBOX'  # Or 'PRODUCTION'