# Generated by Django 4.2.20 on 2025-06-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_upitoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalpaymentanalyser',
            name='billable_count',
            field=models.IntegerField(default=15),
        ),
    ]
