# Generated by Django 4.2.20 on 2025-06-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_digitalpaymentanalyser_billable_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile360report',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
