# Generated by Django 4.2.20 on 2025-06-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_mobile360report_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPIToAccount2',
            fields=[
                ('upi_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
