# Generated by Django 4.2.20 on 2025-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_rcverifyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCVerifyReport2',
            fields=[
                ('vehicle_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
