# Generated by Django 4.2.20 on 2025-07-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_addresstracereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileToDLAdvance',
            fields=[
                ('mobile', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
