# Generated by Django 4.2.20 on 2025-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AadharVerifyReport',
            fields=[
                ('aadhaarNo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
