# Generated by Django 4.2.20 on 2025-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
