# Generated by Django 4.2.20 on 2025-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_bookmark_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='latitude',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='longitude',
            field=models.CharField(null=True),
        ),
    ]
