# Generated by Django 4.2.20 on 2025-06-24 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_bookmark_latitude_bookmark_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='case_description',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='case_type',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='investigator',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
