# Generated by Django 4.2.20 on 2025-06-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_usersession_asn_usersession_batterylevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='FREE', max_length=20),
        ),
    ]
