# Generated by Django 4.2.20 on 2025-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='publicIp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
