# Generated by Django 4.2.20 on 2025-07-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_alter_usersession_publicip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='browser',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True),
        ),
    ]
