# Generated by Django 4.2.20 on 2025-07-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_alter_usersession_browser_alter_usersession_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='latitude',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='longitude',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
