# Generated by Django 4.2.20 on 2025-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0012_alter_usersession_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='cookiesEnabled',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
