# Generated by Django 4.2.20 on 2025-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0013_alter_usersession_cookiesenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='javascriptEnabled',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
