# Generated by Django 4.2.20 on 2025-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudsonrock', '0002_searchbyemail_searchbyusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchByIP',
            fields=[
                ('ip', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchByUsername',
        ),
    ]
