# Generated by Django 4.2.20 on 2025-06-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudsonrock', '0003_searchbyip_delete_searchbyusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchByDomain',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchByUsername',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
