# Generated by Django 4.2.20 on 2025-06-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, default='failed', max_length=10),
        ),
    ]
