# Generated by Django 4.2.20 on 2025-07-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0002_useractivity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
