# Generated by Django 4.2.20 on 2025-07-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0003_useractivity_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='error_message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
